// Even Fibonacci Numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
var i = true; // while var
var f; // 2nd while var
let a = 0;
let b = 1;
let nextNumber = 0;
let FibonacciNumbers = [];
let EvenFibonacciNumbers = [];

while (i) {
    if (a+b < 4000000) {
			nextNumber = a + b;
			FibonacciNumbers.push(nextNumber);
			a = b;
			b = nextNumber;
			i = true;
		} else if (a+b > 4000000) {
			i = false;
            f = true;
		}
};

while (f < 36) {
	if (FibonacciNumbers[f] % 2 === 0) {
		EvenFibonacciNumbers.push(FibonacciNumbers[f])
	}
	f++
};

console.log(EvenFibonacciNumbers.reduce((a, b) => a + b, 0));

// result = 4613732